defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude: 
  - "downloads"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/"
  - "vendor/"
  - "README.md"

keep_files: 
  - "downloads"



